_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 250 # prevents early stopping
max_epochs: 1000

accelerator: gpu
devices: 2

strategy: "ddp"


# mixed precision for extra speed-up
precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

log_every_n_steps: 1

accumulate_grad_batches: 4

gradient_clip_val: 2.0

num_nodes: 1

sync_batchnorm: True