# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.StochasticWeightAveraging.html#lightning.pytorch.callbacks.StochasticWeightAveraging

stochastic_weight_averaging:
  _target_: lightning.pytorch.callbacks.StochasticWeightAveraging
  swa_lrs:
